name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: v${{ github.run_number }}

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${IMAGE_TAG} .
          docker tag ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${IMAGE_TAG} \
                     ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${IMAGE_TAG}
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy safely via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE="${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:v${{ github.run_number }}"

            echo "Deploying version: v${{ github.run_number }}"

            echo "Logging into ECR..."
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
            docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

            echo "Pulling image..."
            docker pull $IMAGE

            echo "Starting temporary container..."
            docker run -d -p 3001:3000 --name temp-container $IMAGE

            sleep 5

            if docker ps | grep temp-container; then
              echo "New container running successfully. Switching..."

              docker stop devops-container || true
              docker rm devops-container || true

              docker run -d -p 80:3000 --restart always \
                --name devops-container $IMAGE

              docker stop temp-container
              docker rm temp-container

              echo "Deployment successful!"
            else
              echo "New container failed. Keeping old version running."
              docker stop temp-container || true
              docker rm temp-container || true
              exit 1
            fi
